# Generated by Django 4.1.3 on 2022-11-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='availabel',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prise',
            new_name='price',
        ),
    ]
